LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/generales/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views

from generales.views import Home, Nosotros, Servicios, Convenios, Contacto, Iniciar_sesion, Proceso_reserva, \
    getDataCombobox, postRegistro, Registro, getDataReserva, Reserva_Finalizada, getBoletin, datosExistente

app_name = 'generales'

urlpatterns = [
    path('', Home, name='home'),
    path('nosotros/', Nosotros.as_view(), name='nosotros'),
    path('servicios/', Servicios.as_view(), name='servicios'),
    path('convenios/', Convenios.as_view(), name='convenios'),
    path('contacto/', Contacto, name='contacto'),
    # path('registro/', Registro.as_view(), name='registro'),
    path('registro/', Registro.as_view(), name='registro'),
    path('proceso_reserva/', Proceso_reserva.as_view(), name='proceso_reserva'),
    path('reserva_finalizada/', Reserva_Finalizada.as_view(), name='reserva_finalizada'),

    path('iniciar_sesion/', auth_views.LoginView.as_view(template_name='generales/iniciar_sesion.html'),
         name='iniciar_sesion'),
    path('logout/', auth_views.LogoutView.as_view(template_name='generales/nosotros.html'), name='logout'),

    path('reiniciar_contrasena/',
         auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html',
                                              html_email_template_name='registration/password_reset_email.html'),
         name='password_reset'),

    path('postRegistro/', postRegistro, name="postRegistro"),
    #path('postReserva/', postReserva, name="postReserva"),
    path('getDataCombobox/', getDataCombobox, name="getDataCombobox"),
    path('getDataReserva/', getDataReserva, name="getDataReserva"),
    path('getBoletin/', getBoletin, name="getBoletin"),
    path('datosExistente/', datosExistente, name="datosExistente"),
    #path('getMedicos/', getMedicos, name="getMedicos"),


]

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/lindasonrisa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', include('generales.urls')),
                  path('perfil/', include(('perfil.urls', 'perfil'), namespace='perfil')),
                  path('admin/', admin.site.urls),

                  path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(),
                       name='password_reset_done'),
                  # solo para reverse match
                  path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('contrasena_reestablecida/', auth_views.PasswordResetCompleteView.as_view(
                      template_name='registration/password_reset_complete.html'), name="password_reset_complete"),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/perfil/urls.py
from django.urls import include, path

from perfil.views import Perfil, getDataPerfil, postPersonal, postCorreo, postDocumentos, correoExistente, anularReserva

urlpatterns = [
    path('', Perfil.as_view(), name='perfil'),

    # métodos get
    path('getDataPerfil/', getDataPerfil, name='getDataPerfil'),
    path('correoExistente/', correoExistente, name='correoExistente'),

    # métodos post
    path('postPersonal/', postPersonal, name='postPersonal'),
    path('postCorreo/', postCorreo, name='postCorreo'),
    path('postDocumentos/', postDocumentos, name='postDocumentos'),
    path('postDocumentos/', postDocumentos, name='postDocumentos'),
    path('anularReserva/', anularReserva, name='anularReserva'),

]

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/generales/forms.py
from django import forms
from .models import Suscribir, Contacto_Form, Usuario


class formBoletin(forms.ModelForm):
    class Meta:
        model = Suscribir
        fields = ('boletin', 'nombre')


class formContacto(forms.ModelForm):
    class Meta:
        model = Contacto_Form
        fields = ('nombre', 'asunto', 'mensaje')

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/generales/views.py
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Suscribir, Contacto_Form, Region, Comuna, Genero, User, Usuario, DocumentoCliente, Servicio, Modulo, \
    Reserva, Suscribir, Proveedor, AspNetUser, AspNetUserRole, AspNetRole
from .forms import formBoletin, formContacto
from django.http import JsonResponse

from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.db import connection
import cx_Oracle
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def send_email(mail, nombre):
    context = {'nombre': nombre}
    template = get_template('correos/boletin.html')
    content = template.render(context)
    email = EmailMultiAlternatives(
        '¡Gracias por suscribirte a Linda Sonrisa!',
        'Linda Sonrisa',
        settings.EMAIL_HOST_USER,
        [mail]
    )
    email.attach_alternative(content, 'text/html')
    email.send()


def Home(request):
    lista = []
    if request.method == 'POST':
        mail = request.POST.get('boletin')
        nombre = request.POST.get('nombre')
        for idx, e in enumerate(Suscribir.objects.all()):
            lista.append(e.boletin)
            pass
        if mail in lista:
            return render(request, 'generales/home.html', {})
        else:
            print("no existe el correo:", mail)
        send_email(mail, nombre)
    if request.is_ajax():
        form = formBoletin(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            data = {
                'message': 'form is saved'
            }
            return JsonResponse(data)

    return render(request, 'generales/home.html', {})


def email_contacto(nombre, asunto, mensaje):
    context = {'nombre': nombre, 'asunto': asunto, 'mensaje': mensaje}
    template = get_template('correos/contactar.html')
    content = template.render(context)
    email = EmailMultiAlternatives(
        asunto,
        nombre,
        settings.EMAIL_HOST_USER,
        [settings.EMAIL_HOST_USER]
    )
    email.attach_alternative(content, 'text/html')
    email.send()


def Contacto(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        asunto = request.POST.get('asunto')
        mensaje = request.POST.get('mensaje')
        email_contacto(nombre, asunto, mensaje)
    if request.is_ajax():
        form = formContacto(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            data = {
                'mensaje': 'el correo ha sido enviado'
            }
            return JsonResponse(data)
    return render(request, 'generales/contacto.html', {})


class Nosotros(generic.TemplateView):
    template_name = 'generales/nosotros.html'

    def get_context_data(self, **kwargs):
        clientes_satisfechos = Reserva.objects.count()
        servicios = Servicio.objects.count()
        proveedores = Proveedor.objects.count()
        context = super().get_context_data(**kwargs)
        #context['contador'] = Servicio.objects.all()
        context = {
            "clientes": clientes_satisfechos,
            "servicios": servicios,
            "proveedores": proveedores
        }
        return context


class Servicios(generic.ListView):
    paginate_by = 3
    model = Servicio
    template_name = 'generales/servicios.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['servicios'] = Servicio.objects.all()
        return context


class Convenios(generic.TemplateView):
    template_name = 'generales/convenios.html'


class Iniciar_sesion(generic.TemplateView):
    template_name = 'generales/iniciar_sesion.html'


class Registro(generic.TemplateView):
    template_name = 'generales/registro.html'


class Reserva_Finalizada(generic.TemplateView):
    template_name = 'generales/reserva_finalizada.html'


class Proceso_reserva(LoginRequiredMixin, generic.TemplateView):
    template_name = 'generales/proceso_reserva.html'
    login_url = 'generales:iniciar_sesion'

    def post(self, request):
        user = request.user
        servicio = request.POST.get('servicio')
        medico = request.POST.get('medico')
        horarios = request.POST.get('horarios')
        diaNombre = request.POST.get('diaNombre')
        # STOCK PROCEDURE PARA OBTENER ID DEL USUARIO #
        d_cursor = connection.cursor()
        cursor = d_cursor.connection.cursor()
        out_args = cursor.var(int)
        resultIdUser = cursor.callproc("sp_usuario_id", [user.id, out_args])[1]
        ####
        # STOCK PROCEDURE PARA OBTENER ID DEL MODULO #
        d_cursor = connection.cursor()
        cursor = d_cursor.connection.cursor()
        out_args = cursor.var(int)
        resultIdModulo = cursor.callproc("sp_modulo_id", [servicio, medico, horarios, diaNombre, out_args])[4]
        ###
        fue_anulada = 0
        fecha_reserva = request.POST.get('dia')
        hora = request.POST.get('horarios')
        usuario_id = resultIdUser
        reserva = Reserva(fue_anulada=fue_anulada, fecha_reserva=fecha_reserva, modulo_id=resultIdModulo,
                          usuario_id=usuario_id, hora=hora)
        reserva.save()
        return HttpResponseRedirect("../reserva_finalizada")
        # return render(request, self.template_name)


def insertDocumentos(ruta, tipo_doc, usuario_id):
    documents = DocumentoCliente(ruta=ruta, documento_id=tipo_doc, usuario_id=usuario_id)
    return documents


def postRegistro(request):
    if request.method == 'POST':
        es_extranjero = request.POST.get('extranjero')
        if es_extranjero == "on":
            es_extranjero = 1
        else:
            es_extranjero = 0
        username = request.POST.get('rut')
        pwd = request.POST.get('password')
        correo = request.POST.get('correo')
        user = User.objects.create_user(username=username, password=pwd, email=correo)
        user.save()

        id_user = user.id
        nombre = request.POST.get('nombre')
        p_apellido = request.POST.get('apellidoPaterno')
        p_materno = request.POST.get('apellidoMaterno')
        fecha_nacimiento = request.POST.get('fecha_nacimiento')
        fono_fijo = request.POST.get('numFijo')
        fono_movil = request.POST.get('numMovil')
        direccion = request.POST.get('direccion')
        id_genero = request.POST.get('genero_id')
        id_comuna = request.POST.get('comuna_id')
        user_extend = Usuario(nombre=nombre, ap_paterno=p_apellido, ap_materno=p_materno,
                              fecha_nacimiento=fecha_nacimiento, fono_fijo=fono_fijo,
                              fono_movil=fono_movil, direccion=direccion,
                              genero_id=id_genero, comuna_id=id_comuna, user_id=id_user, es_extranjero=es_extranjero)
        user_extend.save()

        id_user_extend = user_extend.id
        if 'afp' in request.FILES:
            docs = insertDocumentos(ruta=request.FILES['afp'], tipo_doc=1, usuario_id=id_user_extend)
            docs.save()
        if 'liquidaciones' in request.FILES:
            docs = insertDocumentos(ruta=request.FILES['liquidaciones'], tipo_doc=2, usuario_id=id_user_extend)
            docs.save()
        if 'finiquitos' in request.FILES:
            docs = insertDocumentos(ruta=request.FILES['finiquitos'], tipo_doc=3, usuario_id=id_user_extend)
            docs.save()
        if 'salud' in request.FILES:
            docs = insertDocumentos(ruta=request.FILES['salud'], tipo_doc=4, usuario_id=id_user_extend)
            docs.save()
        if 'c_pasaporte' in request.FILES:
            docs = insertDocumentos(ruta=request.FILES['c_pasaporte'], tipo_doc=5, usuario_id=id_user_extend)
            docs.save()
        if request.is_ajax():
            data = {
                'mensaje': 'datos guardados'
            }
            return JsonResponse(data)


def getDataCombobox(request):
    if request.method == 'GET':
        regionList = Region.objects.all()
        regiones = []
        for r in regionList:
            regiones.append({"id": r.id, "titulo": r.titulo})
            pass
        # Info comunas
        comunaList = Comuna.objects.all()
        comunas = []
        for c in comunaList:
            comunas.append({"id": c.id, "titulo": c.titulo, "id_region": c.region_id})
            pass
        # Info genero
        generoList = Genero.objects.all()
        generos = []
        for g in generoList:
            generos.append({"id": g.id, "titulo": g.titulo})
            pass
        lista = ({"regiones": regiones, "comunas": comunas, "generos": generos})
        return JsonResponse(lista, safe=False)


def getDataReserva(request):
    if request.method == 'GET':
        moduloList = Modulo.objects.all().filter(disponible=1).order_by('hora_inicio')
        modulos = []
        for m in moduloList:
            modulos.append({
                "id": m.id,
                "hora_inicio": m.hora_inicio,
                "hora_termino": m.hora_termino,
                "box": m.box,
                "disponible": m.disponible,
                "dia_id": m.dia_id,
                "servicio_id": m.servicio_id,
                "usuario_id": m.usuario_id
            })
        # Procedure servicios
        d_cursor = connection.cursor()
        cursor = d_cursor.connection.cursor()
        out_args = cursor.var(cx_Oracle.CURSOR)
        resultServicios = cursor.callproc("sp_servicios", [out_args])[0]
        l_servicios = []
        for l in resultServicios:
            l_servicios.append({"id": l[0], "nombre": l[1]})
            pass
        # Procedure medicos

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/generales/templates/generales/proceso_reserva.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <title>Linda Sonrisa</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1 maximum-scale=1 minimum-scale=1"/>
    <link rel="shortcut icon" href="{% static 'base/images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'base/images/favicon.ico' %}" type="image/x-icon">

    <script src="https://code.jquery.com/jquery-3.0.0.js"></script>

    <link rel="stylesheet" href="{% static 'base/js/jqwidgets/styles/jqx.base.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'base/css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/jquery.timepicker.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'base/js/jqwidgets/styles/jqx.base.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'base/css/propio.css' %}">
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css'>
    <link rel="stylesheet" href="{% static 'base/reserva/reserva.css' %}">
    ,
    <link rel="stylesheet" href="{% static 'base/js/jqwidgets/styles/jqx.darkblue.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'base/js/jqwidgets/styles/jqx.material.css' %}" type="text/css"/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a href="{% url 'generales:home' %}"><img alt="logo" id="logo"
                                                  src="{% static 'base/images/logo.jpg' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation" id="text-nav">
            <span class="oi oi-menu" id="text-nav"></span> Menú
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:home' %}" class="nav-link">Inicio</a>
                </li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:nosotros' %}"
                                                       class="nav-link">Nosotros</a></li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:convenios' %}"
                                                       class="nav-link">Convenios & Promociones</a></li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:contacto' %}"
                                                       class="nav-link">Contacto</a></li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:servicios' %}"
                                                       class="nav-link">Servicios</a></li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'generales:proceso_reserva' %}"
                                                       class="nav-link">Reserva</a></li>
                <li class="nav-item" id="hovermenu"><a href="{% url 'perfil:perfil' %}"
                                                       class="nav-link">
                    {% if user.is_authenticated %}
                        ¡Bienvenido {{ user.usuario.nombre }}!
                    {% else %}
                        Iniciar sesión
                        </a></li>
                    {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="hero-wrap hero-bread" id="bannerReserva"
     style="background-image: url('../static/base/images/banner_reserva.jpg');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
            </div>
            <h1 class="mb-0 bread" id="titulo_reserva">Reserva tu hora</h1>
        </div>
    </div>
</div>
<br>

<div class="container" id="contenedor_reserva">
    <form class="form" method="POST" id="formReserva">
        {% csrf_token %}
        <div class="row">
            <div class="col"><p><img class="izquierda" src="{% static 'base/images/uno.png' %}">Seleccione un servicio
            </p>
                <div id='cbxServicio' name="servicio"></div>
            </div>
            <div class="col"><p><img class="izquierda" src="{% static 'base/images/tres.png' %}">Eliga un día para
                reservar
                hora</p>
                <div id='calendario' name="fecha">
                </div>
                <input type="text" name="dia" id="dia">
                <input type="text" name="diaNombre" id="diaNombre">
                <p id="noDisponible">No existen horas en esta fecha. Por favor seleccione otra fecha.</p>
                </div>
                <p id="p_fecha"></p>

            <div class="w-100"></div>
            <div class="col"><p><img class="izquierda" src="{% static 'base/images/dos.png' %}">Seleccione un médico</p>
                <div id='cbxMedicos' name="medico"></div>
            </div>
            <div class="col"><p><img class="izquierda" src="{% static 'base/images/cuatro.png' %}">Seleccione una hora
            </p>
                <div id='cbxHorarios' name="horarios"></div>
            </div>
        </div>
        <br>
        <input type="submit" value="Reservar hora" class="btn btn-primary" id="submitReserva" onclick="validarReserva();">
        <br>
        <br>
        <div class="alert alert-danger" role="alert" id="alertReserva">
            Por favor, todos los datos son obligatorios.
            <p id="p_servicio">- Error al seleccionar servicio.</p>
            <p id="p_medico">- Error al seleccionar médico.</p>
            <p id="p_fecha">- Error al seleccionar día.</p>
            <p id="p_horario">- Error al seleccionar horario.</p>
        </div>
    </form>
</div>


<footer class="ftco-footer ftco-section">

    <div class="container" id="footer" style="display:block;">
        <div class="row">
            <div class="mouse">
                <a href="#" class="mouse-icon" id="footer" style="display:block;">
                    <div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
                </a>
            </div>
        </div>
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Linda Sonrisa</h2>
                    <p>¡Encuéntranos en nuestras redes sociales!</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">¿Tienes alguna pregunta?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><a href="https://g.page/OdontologiaCordilleraPuente?share" target="_blank"><span
                                    class="icon icon-map-marker"></span><span class="text">Av. Concha Y Toro
                                            2279, Puente Alto, Región Metropolitana</span></a>
                            </li>
                            <li><a href="tel://600 500 4582"><span class="icon icon-phone"></span><span
                                    class="text">600 500 4582</span></a></li>
                            <li><a href="mailto:info@lindasonrisa.cl"><span class="icon icon-envelope"></span><span
                                    class="text">info@lindasonrisa.cl</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    | Linda Sonrisa
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

<div class="loader-page"><br><br><br>Por favor, espere mientras cargamos los datos...</div>
</body>
<script>
    function esconder() {
        $('.mouse').css({
            'display': 'none'
        });
    }

    window.onload = function () {
        esconder();
    };
</script>

<script type="text/javascript" src="{% static 'base/reserva/reserva.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/scripts/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxcore.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxbuttons.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxscrollbar.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxlistbox.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxcombobox.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxdatetimeinput.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxcalendar.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/jqxtooltip.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jquery.waypoints.min.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jquery.magnific-popup.min.js' %}"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/globalization/globalize.js' %}"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/globalize/0.1.1/cultures/globalize.culture.es-ES.js"></script>
<script type="text/javascript" src="{% static 'base/js/jqwidgets/globalization/globalize.js' %}"></script>

<script src="{% static 'base/js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'base/js/aos.js' %}"></script>
<script src="{% static 'base/js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'base/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'base/js/scrollax.min.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>


</html>

LindaSonrisaWeb/lindasonrisa proyecto/proyecto/lindasonrisa/generales/templates/generales/reserva_finalizada.html
{% extends 'base/base.html' %}
{% load static %}
{% block titulo %}
    Linda Sonrisa - Reserva Finalizada
{% endblock %}

{% block content %}
    <div class="container">
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">¡Reserva realizada!</h4>
            <p>Una vez realizada la reserva, puedes visualizar en tu perfil, en el módulo "Mis reservas" el contenido de
                las reservas solicitadas.
                Puedes ir directamente a tu perfil <a href="{% url 'perfil:perfil' %}" class="alert-link">aquí</a></p>
            <hr>
            <p class="mb-0">También puedes solicitar una nueva reserva haciendo click <a
                    href="{% url 'generales:proceso_reserva' %}" class="alert-link">acá</a></p>
        </div>
    </div>
    <script>
    function esconder() {
        $('.mouse').css({
            'display': 'none'
        });
    }

    window.onload = function () {
        esconder();
    };
</script>
{% endblock %}